### ISSUE TITLE
wizard: registering a global account fails

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#10]
i always get this error (red error timeout) after a while when trying to register a new available global username:
![screenshot_20170421_165027](https://cloud.githubusercontent.com/assets/840070/25283805/502731ba-26b5-11e7-8906-513a9cca040f.png)

Now my network works fine, and i have added a local account already, so not sure why it fails to have a global account.

**Comment by Elv13** [comment]
If it gets red it means at least the last issue has been resolved. Can I have the daemon and client logs? Without them there is little I can do. I did extensive testing locally and on VMs and it seems rather reliable to me.

**Comment by star-buck** [comment]
as concluded in the other packaging thread, i believe once packaging in a reliably and transparent way is solved, this also should be solved and from then on result in packages that are relaibly testable.

So I am waiting for shadeslayer to show up on IRC and let me know where I can get the latest packages to test it again.

**Comment by Elv13** [comment]
I really don't wish to open the debate again, I have no intention to provide public packages and/or spend any time on the framework to generate them. Those are the build artifact of my build cluster, nothing else.

That being said, in case you wish to test now http://184.160.93.215:8080/netrunner/ring-kde_16.12.0-1_amd64.deb should help with that. It is *not* intended for regular use and is a **instrumented build** (https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html), so it's **slower**.

**Comment by star-buck** [comment]
works with new ring-kde package
