### ISSUE TITLE
Create new daemon nightlies .deb

### ISSUE THREAD

**Issue by Elv13** [banji-project/ring-issues#15]
@shadeslayer First, sorry to ask anything, I know you are probably busy.

Until a few weeks ago, upstreamed seemed to support a `packaging` branch in that daemon that actually produced working `.deb` when executed in docker. However since many days, it's broken and nobody will fix it / maintain it anymore. I used that to take my screenshot/screencast and test a "clean" environment.

I tried to adapt your packages from https://github.com/ds9-extras-packaging/ring, however I lost a lot of time and it seems they broke something hard... Trying to fix the old packages also resulted in endless linking errors. For now I ended up doing a `dpkg -i` from the wrong distribution and force-installed it (debian sid -> 16.04). It *works* but obviously produces broken tests and could probably crash. You are the expert, so could you please take a look?

What I need is a package from Git, not the tarball and not with the bundled stuff like libringclient. Also please target Neon, the latest netrunner ISO fails to start X11 (or Wayland) on my laptop while for some reasons the latest Neon ISO works (the laptop is 5 years old, so this is strange, but also off topic).

I am kind of stuck here. I need nighties because otherwise the tests are worthless (they keep changing the behavior), installing the daemon "by hand" on a live-cd takes an hour each time and using the wrong packages will only cause extra crashes.

**Comment by star-buck** [comment]
@Elv13 : 
unfortunately Rohan can't build Neon packages on DCI.
You somehow need to get Netrunner working for us to build and test nightlies.

**Comment by star-buck** [comment]
@Elv13 : to get this going and keep contact, please join our channel on IRC freenode #dci-jenkins

**Comment by Elv13** [comment]
> #dci-jenkins

Done

Do you want me to investigate? The error is the classical "no screen found". The reason is rather easy to fix, but the packaging cause it often hard to figure out. Debian: work, Kubuntu: work, Neon: work, Netrunner: error.
