### ISSUE TITLE
GUI: Ongoing status (removing the old GUI completely)

### ISSUE THREAD

**Issue by Elv13** [banji-project/ring-issues#18]
Timeline:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/340384/27376699-f6f190e8-5640-11e7-8d2a-d7291ed2906e.png">

Ringing call:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/340384/27376765-1e2dc08c-5641-11e7-8a1a-53d2a14d9e83.png">

The widget at bottom tracks the call progress and print relevant error if it failed

After the call ended:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/340384/27376814-3d541916-5641-11e7-9147-d1df59f3f834.png">

In call:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/340384/27376967-a36e3844-5641-11e7-8be1-eea3a665268e.png">

Persistent widget to hang up current call while looking at the chat or other users:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/340384/27377024-d13c9ef0-5641-11e7-8944-b9b605ba16aa.png">

Live search with username lookup:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/340384/27377088-f788bc88-5641-11e7-800c-0dd9bfa1afcd.png">

Just press enter and you can already edit the contact, no need for the dialog:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/340384/27377140-1fd07b0e-5642-11e7-9192-8172bc438401.png">

The scrollbar now really works

![image](https://user-images.githubusercontent.com/340384/27377234-6c55f3e6-5642-11e7-99cb-e33cd9ffba94.png)

The search with my test dataset:

![image](https://user-images.githubusercontent.com/340384/27377276-82c1c74a-5642-11e7-8774-e8147568bfd0.png)

A video from yesterday (dark theme, sorry)

https://www.youtube.com/watch?v=Fgg7VPmfxVo&feature=youtu.be

**Comment by Elv13** [comment]
Edit: 
[ring-kde.zip](https://github.com/ring-project/ring/files/1105125/ring-kde.zip)

**Comment by Elv13** [comment]
I updated the link above with the bleeding edge version. The one from Friday had a little crash once in a while. The new package isn't perfect, but at least it doesn't have that crash

**Comment by Elv13** [comment]
[ring-kde.zip](https://github.com/ring-project/ring/files/1105925/ring-kde.zip)

**Comment by UriHerrera** [comment]
Hi @Elv13,

@star-buck asked me to help out with the GUI work. Here's some of the mockups though there's more to make but should get you started on how to make it look native to Plasma like using native UI elements rather than making custom ones.

Account setup # 1:
![](https://i.imgur.com/9iLoyZP.png)

Account setup # 2:
![](https://i.imgur.com/wlKFNO4.png)

Account setup # 3:
![](https://i.imgur.com/fpaedWx.png)

Ring window # 1:
![](https://i.imgur.com/yqEdQg3.png)

**Comment by Elv13** [comment]
Thanks a lot for this. They look very nice. A few thing that probably will need to change:

 * The side tabbar. It was requested by @star-buck and it also being used in many new Kirigami/QML KDE apps such as Kube. 
 * The contactrequest tab and history tabs are not needed. The Gnome client plan to remove them too. The information is integrated in the timeline.

> make it look native to Plasma like using native UI elements rather than making custom ones.

Those are not custom ones. Those part the default QML Controls 2.0 theme on the current Plasma release. QML QtQuick Controls 2.0 doesn't support Breeze yet, it is why it looks different. All applications that use Controls 2.0+ are affected by this and look as everything looks above. Note that there is work being done fixing this by other developer such as Sho and notmart[1], but it isn't ready, yet.

Therefor there is nothing I can do beside writing custom widgets to make them look like the mockups. Unfortunately, QtQuick controls 1.0 and 2.0 are incompatible technologies and 1.x has no future and will be considered deprecated in Qt6. Ring-KDE 3.0 will have to use the "universal" default qqc2 style as shown above. The problem will solve itself once the QPA sets the new "plasma compatible" qqc2 theme to be the new default.

[1] https://cgit.kde.org/qqc2-desktop-style.git/

**Comment by UriHerrera** [comment]
Ah ok, we're working on a Kirigami app. I'll update them.

**Comment by star-buck** [comment]
How about we name it ring-qt?
"Welcome to Ring-Qt, a frontend for the Ring Network."

Also, are we really working on a kirigami app? Lets streamline the
currently used UI first instead of rewriting it yet again.
The sidebar should be used for the tabs therefore, but the most important
mockups would be the content inside the tabs while we keep the basic
structure layout outside of the tabs content for now.

**Comment by Elv13** [comment]
> How about we name it ring-qt?

First of all, renaming an app is complex and require some extra work to make an automatic config porting system, breaks the namespace, dbus paths and confuse users. So this is not to be taken lightly. But most of all, it would be even worst than Ring-KDE. Both the Gnome, Windows and macOS Ring clients uses Qt. They are built on top of sflphone-kde (renamed ring-lrc) just as ring-kde is. The windows client also uses a Qt gui, but its mostly a dead end since the code is one giant ball of a mess.

However renaming the app would probably make sense if you wish to encompass things like emails and other media in the timeline. But that name should probably not use "Ring" in it since that would be a major deviation to what other Ring client do and would confuse users. It should also not use Qt or KDE in the name since such branding piggybacking only make sense for technical people and you repeatedly said you want a boarder audience.

If you don't want to change the name away from Ring, then I would advice not changing it at all. It's more trouble than it's worth (been there, done that).

> Also, are we really working on a kirigami app?

Yes and no. It's currently a QML app without a real "identity". As you wished (and wisely so), all the work so far has been on features rather than design. As of now it's quite wireframe-ish and ugly, so it needs a design.

It doesn't need a "rewrite" to look like Kirigami, just a couple days worth of changes. However that's your decision and I am fine either way. So far I simply ignored the choice. If Marco work on the theme come to fruition, it will look like a classic KDE desktop application. Using qqc2 was a necessary decision. If I had not, the Plasma mobile version would not have been possible. It is also what Qt recommend to use, even if it isn't very mature and well integrated yet.

> The sidebar should be used for the tabs therefore, but the most important mockups would be the content inside the tabs while we keep the basic structure layout outside of the tabs content for now.

Roger that.

Shall I implement the wizard changes or do you prefer the blue one? If I recall, all the mockup you asked me to draw inspiration from were blue (Skype and the Ring-android wizard).

**Comment by UriHerrera** [comment]
Ok so, from a technical perspective the UI can look however we want? @Elv13

**Comment by Elv13** [comment]
Well well well, what a timing!:

http://jriddell.org/2017/09/06/qqc2-desktop-style-beta-release/

I will try it once I get a stable Internet access again. I am at the airport leaving for the Randa meeting, so I will be on IRC on and off for the last 40-somthing hours while I bounce around the world.

> Ok so, from a technical perspective the UI can look however we want? @Elv13

I can say what's possible, but @star-buck says what has to be done. Here are the guidelines I got so far (in my own words). Until said otherwise, those are constraints on your design too:

 * A dark tabbar on the left side looking like Discord/QtCreator/Kube/VSCode/Atom and various Electron based apps
 * Use the same general timeline based layout as the current generation of chat apps (left pane for recent peers and right one for content)
 * Use this type of interface for the chat content, but with more media https://cloud.githubusercontent.com/assets/840070/25556064/2258853a-2cf6-11e7-959d-f120b78e96de.png
 * Use a Skype like video view with round buttons that hides after 3 seconds
 * Have a page to view and edit contact details
 * The wizard as is currently implemented is based on specified requirements (beside the exact colors, spacing and artwork)

For the next milestone (3.1.0 after the initial release):

 * Support mobile form factor
 * Be touch friendly
 * Adaptive design

(this have to be taken into account now)

Extra requirement (related to how Ring works):

 * Everything can arrive in any order and be fixed locally
 * Everything can fail at any point because distributed network behave like that. The UX has to expect it and have room for explanations and retry buttons
 * Some simple steps can take ridiculous amount of time, so a progress indicator and some "entertaining animations" are required to show the app has not frozen.
 * It needs to be future proof and have a flexible UX. Some features and services will be enabled later and should not cause massive interface changes once integrated. File transfer, emails, group chat and voicemails are prime examples.

@UriHerrera Also make sure you seen the current GUI, the screenshot above and ancient https://www.youtube.com/watch?v=AYba9uepFzs

What would be more pressing would be a more iterative approach to making the central canvas look nicer. I will provide you with updated screenshot with the Breeze theme ASAP, but for now just imagine that the widget will suddenly look normal once that missing KDE integration code is finally released.

**Comment by UriHerrera** [comment]
Question, other than the timeline button and the button below it (what does it do?), what else goes into the tabbar? or what else will go into the tabbar?.

**Comment by Elv13** [comment]
The button below the timeline is the addressbook. There is also the history and the bookmark panes, but they are currently disabled as requested by @star-buck. If it was to become a Kirigami app, then there would also need to be a setting. The previous version also had a dialer mode for "real" phone calls, but it will need to be rewritten to QML. The dial pad is required when calling numbers with phone menu. The keyboard works too, but it was proven to be confusing during previous usability studies. Users find a dialpad widget more intuitive.

(Sent from my phone at the airport)

**Comment by star-buck** [comment]
Some thinking:
History and Timeline should be redundant, at least conceptually.
Bookmarks aka Favorites could be integrated into Contacts/Adressbook/People, where the starred ones can be at top or filtered?

**Comment by star-buck** [comment]
Lets concentrate on the two tabs we have though and see to visually refine them. To keep this from grwoing too long, I suggest using seperate issues for timeline and adressbook mockups.

**Comment by UriHerrera** [comment]
Alright so I redesigned the main window.

Timeline
======

I added a tabbar. It has 4 buttons: timeline, dialpad, contacts and settings and the user avatar at the top. It's not dark *but* it's using the colors from the Ring logo. It helps to have the branding integrated in a way in the software.

The timeline is divided in days and within each day the activity by contact ordered chronologically. The activity of each user is inside a message-like bubble, in it the recipient is shown the last message activity by the sender. Below that is the calls activity.

The color of the bubbles by default is gray. I think that the user could set a color for each contact to differentiate them (i.e. the background color and the text color).

![](https://i.imgur.com/hdyrDad.png)

**Comment by Elv13** [comment]
Ah, now that starts to look its heading somewhere! Nice mockup!

Now, lets break this down a bit and improve some areas.

### The information fields

 * I am not sure the full date/time is required. There's already the date above them, so the information is redundant.
 * The peer name isn't standing out enough. I am not saying the photo should be added. Often, there is no photo, so you get the stock contact icon many time in a row. So I am fine if the photo isn't there. However, the eye should quickly see to who the element belong. The big color rectangle catches the eye, but doesn't say who is who.
 * The `User:` field is a bit redundant and misleading. The "people" in that list are not necessarily Ring users. @star-buck also wants emails to be there. There is also random people with phone numbers. So `User:` is not the right word to use.
 * The call count is not very useful in the left area. This is displayed in the main GUI and isn't important enough to require an entire row in the peers timeline. I would suggest to display missed calls and new messages.
 * The bookmarks/favorites. Currently, there is a little star. I would like some "pinned" items to be more visually popping than the "normal" peers. This is an usability trick based on the theory that an average user has a very small "closed circle" of people that are likely to encompass 90% of her/his/it communication. Being able to visually distinguish them from the "noise" tend to make the user happier with the application. There was an usability study about that somewhere, but I can't find it right now. Anyway, it makes sense.

### Color coding

 You chose to use random colors for the rectangle. I wonder if this is such a good idea and if it is, how should the color coding be based on. Most IRC clients use this for the last 30 years to make group chat usable. In that context, it works very well. Here, we don't have this problem. I wonder if it might be too flashy. I am a bit neutral about this. I am fine either way. I will let @star-buck decide.

If we choose to do this. What should be used to select the color palette? I believe starting with the Google Material color guidelines would be a good start. Letting the user choose a custom color (or pattern? or photo?) for a peer would also make sense.

### Menus and toolbars

You removed both the menu and the toolbar. @star-buck asked for a new contact button in the toolbar. However, I tend to agree with you. They should be removed. At least by default.

### Scrollbar

You opted for a persistent scrollbar. Are you sure about this? Don't you think an hover / autohide scrollbar wouldn't be a better option? There is little value in seeing how many peers you have in the peers timeline. You most likely wont ever have to use the scrollbar. The topmost items are usually enough. If there are not, then the search is the only sane way to see find them.

### Dotted timeline

This looks beautiful. This is exactly what I had in mind, except your rendering is less ugly than mine.

So:

@star-buck:

(today, I am working on the appimage, tomorrow, I will work on fixing the accessibility problems as we have the required knowledgeable people available at Randa. I will start working on this soon after).

 * Please share your decision on the toolbar and menu
 * Please share your decision on the peers timeline color coding

@UriHerrera:

 * Please reconsider the relevant information fields present in the color rectangles and update the mockup.
 * See the other comments above and lets see if we can reach a compromise

**Comment by UriHerrera** [comment]
I'll update the mockup.

**Comment by star-buck** [comment]
@Elv13 : 
- yes, i can imagine we dont need the toolbar if we have "add contact" as an entry in the sidebar
- color coding sounds fine as suggested, maybe still add a small picture/avatar, but either is fine

**Comment by Elv13** [comment]
Got it.

Also, the Kube/Sync team arrived at Randa today. We prototyped Ring-KDE email/contact integration this morning. I wont spend more time on this until you approve it, but so far so good. It works rather well actually. Note that the prototype is only the backend, I didn't implemented emails in the timeline yet, so there is nothing to see beside "umm, yes, they are successfully loaded". If I merge that branch, it will be a compile time optional dependency, just like Akonadi currently is.

**Comment by star-buck** [comment]
@Elv13 : sounds great! 
Who exactly is the kube/snyc team in Randa?

**Comment by star-buck** [comment]
lets do email integration after textchat and audio/videochat is done, like a major version 2.0

**Comment by Elv13** [comment]
> Who exactly is the kube/snyc team in Randa?

Christian Mollekopf and Micheal Bohlender

**Comment by UriHerrera** [comment]
* Removed the date from the info. fields.
* Extended the field to include the ID of the sender in bold. It could also say : _Sent by:_ before the ID, username, phone number or email.
* The info. field shows the number of messages not read.
* If there are no call activity the info. fields only show 2 rows. Third row only shows when there's missed calls.

![](https://i.imgur.com/Joq4uGA.png)

My idea is that the user sets colors for their favorite contacts sort of like color tags in other programs like macOS finder or elementary Files. For example in the mockup the fields that use different colors are favorites, the fields that use  ![#90a4ae](https://placehold.it/15/90a4ae/000000?text=+) `#90a4ae` are non-favorites this is also in the dots on the timeline itself.

In the other mockup I added the scrollbar to showcase how it would look like when there are more items in the timeline, if there aren't enough items in the timeline it shouldn't be visible as in this other mockup.

**Comment by Elv13** [comment]
Ok, thanks. Once me and sgclark are done with the appimage I will release beta1 with the old UI. I will start to upgrade the GUI.

One last issue is that hardcoding grey color wont work. It has to follow the system (color) QPalette. Whatever color is there has to work in both light, dark and HiColor themes. 

https://api.kde.org/4.x-api/kdelibs-apidocs/kdeui/html/classKColorScheme.html
http://doc.qt.io/qt-5/qpalette.html#ColorRole-enum

**Comment by UriHerrera** [comment]
> One last issue is that hardcoding grey color wont work. It has to follow the system (color) QPalette. Whatever color is there has to work in both light, dark and HiColor themes.
>
> https://api.kde.org/4.x-api/kdelibs-apidocs/kdeui/html/classKColorScheme.html
http://doc.qt.io/qt-5/qpalette.html#ColorRole-enum

So it can be any color from the color scheme that I can select in System Settings?

![](https://i.imgur.com/jfGjz7G.png)

I used `Inactive Titlebar Text` for the fill and `Inactive Text` for the borders on the gray info. fields from the Breeze color scheme.

**Comment by Elv13** [comment]
> So it can be any color from the color scheme that I can select in System Settings?

The limitations for KDE applications are to avoid hardcoding colors as we have to support both alt color schemes and HiContrast for accessibility reasons (there's laws for this in various countries). Using random colors from the palette may or may not cause issues. In "the real world" we could try to use colors that looks like in both light and dark mode and have an alternate sets for High Contrast users. This should allow to ignore the problem.

"Modern" design HIG seem to avoid using the old palette concept that's in use since Windows 3.1. Google Material has well documented light and dark favored colors instead of forcing them from the toolkit. QtWidgets / Win32 / .NET / Cocoa still use the system palette concept.

So I am *not* against using custom colors, but *I am* against hardcoding the whole design. This voids our application guidelines and is a no go for a KDE app. If we can come up with a compromise that supports all 3 "common" type of look (light/dark/HighContrast), then it's fine. However, the QPalette should always be favored for common colors (all greys background, text and panel background).

**Comment by UriHerrera** [comment]
I'll add a mockup with the colors from the High Contrast color palette.

----

Update:

![](https://i.imgur.com/M0Ow0Bv.png)

Here I used the colors from the High Contrast palette in Plasma.

**Comment by UriHerrera** [comment]
![](https://i.imgur.com/eL4Ix2t.png)

Or could be like this: Don't force the colors but just add a star to the favs. Much simpler.

**Comment by star-buck** [comment]
since the ground work has been laid, lets close this here and evaluate each main screen option in detail in seperate topics after alpha1 appimage gets shipped.
