### ISSUE TITLE
start-window pops up behind main window: the main window should not popup at all when the startscreen is shown.

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#2]
- the startscreen should always load first to show the welcome slide.
- even if an acfcount has already been added, the startscreen should appear first and prevent the main client window from popup
- when an account has been already added before, the screen simply shows the welcome slide and when pressing enter or clicking somehwere, only then the normal client is loaded and shown.

- later, when we add a local login, we can always show the second options slide, where one could simply login to an already exisiting local account, add a new account or transfer an already existing remote account.

**Comment by Elv13** [comment]
I will do it if you wish so, however I am not sure if this is such a good idea until the Ring daemon gains support for local decryption. If I was a user, I would consider this popup to be rather annoying. Here's some counter arguments I would like you to consider before saying "please do it anyway":

 * Ring has no login. It uses key-pair authentication when calls are negotiated.
    * The proposed "fake login" would only prevent local account from being used by people with physical access and thus is redundant of the KDE lock screen. 
    * It isn't implemented anywhere in the stack, so the popup would not serve any purpose until the daemon is patched (slow process, a month of waiting).
    * It also would not add any "real" security as a potential malicious actor with control of the computer would steal the private key from memory or use a keylogger to steal the password. In infosec, it is acknowledged that when the computer is compromised, the game is over.
 * Account management is part of the setting. If multi-device is the only use case for the popup, I would argue that the account setting page serve this better.
 * Usability wise, multi-window applications are not very "trendy" at the moment. Most "modern" applications try to stick to a single window, including the dialogs. Studies have shown that popups cause a mental context switch and slow down most workflows.
 * The current default Ring-KDE "call canvas" already has a welcome message. It could be merged with the welcome screen.

Thus, my advice would be not to show the welcome screen once an account exist or skip has been pressed. *Or* I can add a checkbox `Don't show this dialog again` as a middle ground.

**Comment by star-buck** [comment]
Like gimp, krita, etc. Always show the welcome screen.
Then load either the client and once loaded close the welcome again
automatically if an account exists or go automatically to the options
screen without loading the client until the wizard is finished.

**Comment by star-buck** [comment]
so the welcome screen does popup in front now and the ring-kde client only becomes visible when the startscreen is closed. this ticket is done then , as for the other question wether to always load the welcome screen ill open another ticket.
