### ISSUE TITLE
unable to reach any external account, make calls, send message, etc.

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#28]
I tried reaching my android ring account, but even though my android account is 100% online and fine, neither can the ring-app reach that account, not can i reach that ring-kde.

**Comment by Elv13** [comment]
Hello,

I will need the logs for that one (you can email them to me to avoid posting private data)

Also, was it using the version with demo data or the normal version? Only the normal version is expected to work properly.

**Comment by star-buck** [comment]
i assume its this:
the appimage quits when registering a public account, therefore it doesnt register correctly and then fails to do anything here.
And yes, this is not the demo.

**Comment by star-buck** [comment]
dependent on this bug: https://github.com/ring-project/ring/issues/22

**Comment by Elv13** [comment]
Then I will need the backtrace for this, it definitely does not crash here. You can run the appimage in gdb

```
gdb path/to/appimage
run
# make it crash
backtrace
```

**Comment by star-buck** [comment]
this is all i can get you:
https://pastebin.com/fRGidSxC

It happens reproducible whenever there is a valid not yet registered account, you enter both passwords correct, and hit "Next", it quits.

**Comment by Elv13** [comment]
Umm, I can't seem to reproduce it on Debian9/Ubuntu1804/Neon1604/Gentoo. I really need the backtrace. 

```
gdb ./ring-kde_3.0.0-alpha3-x86_64-X.appimage 
run
thread apply all bt full
quit
```

The log says that it crash when creating the account (obviously) and the last message is from LibRingQt just before it calls into the LibRing (daemon). Then it spawn something like 9 threads and pinpointing what goes wrong require more info. It looks like an upstream bug, but you assigned me to this, so I will fix it anyway.

It doesn't seem to be related to the registered name to me. It looks like a race condition when generating the certificates

**Comment by star-buck** [comment]
To test yourself, just download Netrunner Rolling 2018.01 and see it fail.
Maybe something is missing.
I guess Manjaro or Arch will fail too.
