### ISSUE TITLE
show "welcome splash" for 3-4 seconds when loading the ring-kde client (then continue to show the client if an account exists or continue with the wizard page if no account exists yet)

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#3]
as an example, here is how skype on linux welcome screen always starts in the center, same size, even if you move it:
https://www.dropbox.com/s/gw7i9e1lsw4wnm1/skype-startscreen.mkv?dl=0

The splash screen could also displayed as the "About Ring-KDE".
So the splash doesnt carry any other method like login, it stays as is as a frontscreen to the login+accounts window when starting up.
Then when the account wizard is started from WITHIN the client, it doesnt need the local login, so it all creates too much wiggle at this point)

Implementation for now:
Simply show the welcome splash screen for 3-4 seconds that then 
- continues with the wizard page when no account has been setup yet or 
- simply closes and shows client.

**Comment by Elv13** [comment]
Hello, just a little detail.

Please pick one of the possible solutions.

## Conceptual issues

There is 3 different concepts here.

#### Splash screen

A splash screen is a concept from the 80's to display a static pixmap (with or without a progressbar) while the application load. This is mostly out of style as applications now load fast enough. Only a few application still uses one.

 * Gimp (load some python plugins and re-index a few directory)
 * Digikam (load a whole database in memory and `stat()` all pictures for changes.

Most application that start faster stopped using this concept. Qt still supports it[1]. This is the concept that is usually auto-hidden once the loading is complete.

#### A wizard / modal dialog

Something you run on the first run and help setup the application. It is usually not the same thing as a login dialog, even if they can/could share the same window. A wizard is a `QDialog` or `QWindow::setType(dialog)` objects. Those type of window are not expected (neither by the WM or by the user) to be auto hidden.

#### A mandatory login page

Used to protect access to assets. Cannot be bypassed. Can have a little welcome page for a few seconds.

## Possible solutions

#### Integrate the welcome page into the main window

This would avoid the popup and focus stealing events that comes with it. It would fill the call canvas until the user take action (click on it or press any key).

#### Delay the introduction of this feature until the login is implemented

Given the video feature is progressing well and the original stated goal of the wizard are close to completion, this login feature, if you really wish to have it, could be the next feature on the list. The welcome page and login page would then make more sense than a focus stealing modal dialog used as a splash screen.

[1] http://doc.qt.io/qt-5/qsplashscreen.html

**Comment by star-buck** [comment]
Lets forget the local login for now, as it has many consequences to implement this simple splash screen PLUS the local login. 
(like: the welcome splash screen should STILL be displayed then a few seconds before the account wizard opens up.
The splash screen could also displayed as the "About Ring-KDE".
So the splash doesnt carry any other method like login, it stays as is as a frontscreen to the login+accounts window when starting up.
Then when the account wizard is started from WITHIN the client, it doesnt need the local login, so it all creates too much wiggle at this point)

Implementation for now:
Simply show a splash screen for 3-4 seconds that then shows the wizard when no account has been setp yet or simply closes and shows client.

**Comment by Elv13** [comment]
ok, I will take care of that tomorrow

**Comment by Elv13** [comment]
Here's a basic splash screen. I can add more details (copyright, authors, version, etc...). Of course the image should change eventually, but this is about the feature itself.

![pick11](https://cloud.githubusercontent.com/assets/340384/25220743/bbe63ae4-2580-11e7-96d4-ca86f9428f25.png)

**Comment by star-buck** [comment]
The function is almost correct, but we simply should take the same welcome frontpage as startup screen that is already used when no account has been setup (the ones before the wizard page):
![screenshot_20170421_164906](https://cloud.githubusercontent.com/assets/840070/25283210/466dcd0c-26b3-11e7-969a-35da20a3c458.png)


So ring-kde always starts with this initial welcome screen and then either when PRESSED or after 3-4 seconds it continues either with the client or continues like it does now already with the wizard screen if no account has been setup yet.

**Comment by star-buck** [comment]
@Elv13 : What is the update on this?

**Comment by Elv13** [comment]
It is done

**Comment by star-buck** [comment]
great, please mark things done with the green label to easier spot what is ready fopr testing.
Once confirmed on another machine to work, I'll close any issue which has been 
- coded
- properly packaged
- could be installed
- and confirmed to work.

**Comment by Elv13** [comment]
Done
