### ISSUE TITLE
contacts: add photo: doesnt save picture selected

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#31]
added a photo:
![screenshot_20180220_121916](https://user-images.githubusercontent.com/840070/36421314-4d84f5b4-1638-11e8-8ceb-d1423e75ffaa.png)
but still looks the same:
![screenshot_20180220_121902](https://user-images.githubusercontent.com/840070/36421323-52c3e03a-1638-11e8-91e2-9eef707c009c.png)

**Comment by Elv13** [comment]
whoops, regression from a change late last night. Saving images is fixed.

**Comment by star-buck** [comment]
it doesnt seem to work here...

**Comment by Elv13** [comment]
It works when you select a rectangle by clicking on the picture once it's selected. However I agree this is unexpected and has to be done automatically when not done manually. The RFC enforces that images have to be squares (meh, 90's idea, whatever).
