### ISSUE TITLE
Profile Picture: auto fit the format to make it compatible, regardless of which picture the use selects or the camera provides

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#34]
add option to change profil picture here:
![screenshot_20180220_121707](https://user-images.githubusercontent.com/840070/36421262-17937e94-1638-11e8-9955-29ce842b0b63.png)

show here if set:
![screenshot_20180220_121728](https://user-images.githubusercontent.com/840070/36421276-2411812a-1638-11e8-8724-7ed9038ab5a9.png)

**Comment by Elv13** [comment]
done

**Comment by star-buck** [comment]
i still cant save it, it stays empty

**Comment by star-buck** [comment]
still, this doesnt work?
I and also any user doesnt care in todays times that the picture must be any number of given pixels or squared, it is 100% assumed the program does make it so regardless what the user selects as picture from file or camera.
This doesnt work in ring, so it your responsibility to make this work, either by shrinking the file and OF COURSE skewing it thereby to fit square if thats required or offer a selection grid to cut out the desired format.
Either way, it needs to be solved by ring-kde and not leave it up to the user.

**Comment by star-buck** [comment]
okay, seems it DOES work... not sure why it didnt save or rejected the pictur in the first place... now it does seem a picture added stays in the avatar profile picture display.
Will investigate further if the former is reproducible, otheriwse close this ticket.
