### ISSUE TITLE
Favorites: clicking on a person doesnt change context

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#36]
![screenshot_20180220_152557](https://user-images.githubusercontent.com/840070/36429222-706371cc-1652-11e8-830c-f580002afe94.png)

**Comment by Elv13** [comment]
Duplicate of #23, I am not done with this feature. I moved on to the other ones has I perceived them as being an higher priority after a quick bookmark panel prototype. There is still 1-1.5 day of work to complete this feature. For now it's barely showing and updating/saving correctly.

**Comment by star-buck** [comment]
this is a much bigger issue and more relevant than sorting and search for "favorites".
Please keep this ticket open and we can add anything else that is more a feature like sorting when other stuff is done.

**Comment by Elv13** [comment]
done

**Comment by star-buck** [comment]
works
