### ISSUE TITLE
move own small video from left to right corner + ALWAYS show it and not hide it with the other overlays

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#37]
currently, its in left corner and hides with the other overlays:
![screenshot_20180220_153315](https://user-images.githubusercontent.com/840070/36429631-808e8b08-1653-11e8-9e04-d2554fb7727f.png)

**Comment by Elv13** [comment]
partially done, it no longer gets hidden with the toolbars. I actually never noticed! Someone to see things all day and you stop seeing them...

**Comment by star-buck** [comment]
works okay

**Comment by star-buck** [comment]
lets move own video window to right side as in gnome-ring:
![screenshot_20180221_122723](https://user-images.githubusercontent.com/840070/36477791-c9bcdd34-1702-11e8-8d30-02c49b94b230.png)

**Comment by Elv13** [comment]
done

**Comment by star-buck** [comment]
please mark done tickets with the green label, thanks.
