### ISSUE TITLE
left sidebar: remove "Dialer" and make ring-kde a ring client by name only

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#40]
to reduce complexity, lets remove any "general phone center" SIP-stuff like the dialer, but also adress, company, name, organization, etc. as thats all overhead that in a classical whatspapp/skype replacement nobody uses.
This simplifies the client tenfolds and makes it possible to actually finish a 3.0 RC in time.

**Comment by Elv13** [comment]
Just the dialpad or the whole panel?

Keep in mind that if the whole panel is removed, it's no longer possible to
manage video between more than 2 person. It's also the place where missed
calls and some errors are listed. It will have to be moved somewhere else
if that's removed.

Taking into account missed calls, ongoing calls, multi-party-calls and
error handling are important elements, I doubt completely removing the tab
is a good idea until/unless these features are seamlessly integrated
elsewhere. I also think that adding them on top of the "people manager"
tabs will add more clutter than having them in there own little sandbox tab.

Removing the dial pad itself is however a no brainer and doesn't have side
effect. It was already disabled by default until you asked me on 29/04/2017
(by email) to enable it by default.

I suggest to disable the dial pad but keep the tab.

For the organization and address, I agree. I have been thinking about
making adding those things optional and hidden behind the (+) button to
remove the clutter and free up the space. Very few people indeed care about
those things. The statistic part will eventually go the way of the dodo
too. It's not very useful and take up prime real estate.

**Comment by Elv13** [comment]
What is your idea to integrate the following feature elsewhere. 
Those things have to go *somewhere* if they are no longer there.

Please decide / comment on the following alternatives. Feel free to suggest other possibilities.

### The missed calls

Possible alternatives:

 * Integrate them in the peers timeline
 * Use persistent XDG notifications
 * Improve the history tab of each contact to reflect them
 * Restore the "real" history dock / sidebar and put them there **(preferred)**

### The errors when a call/chat/whatever just stop

Currently they appear for 3 seconds in the audio/video main media view and then the media buttons appear again.

A change could be made to make the error information permanent until manually dismissed.

### How to handle / manage multi-party video chat

This is the main use case of the dial view. If you don't care about this feature, it can be disabled. There is no other pathway in the GUI to enable this multi party video chat / conference calls.

A middle ground compromise would be to show the dial view tab only after the user press a currently non-existent "add participant" button during a video chat session.

**Comment by star-buck** [comment]
How about you move the search field for new or existing ring-ids only there to the dialer section?

So "Find someone" is shown and active only in that section and you remove it from the other sections, like bookmarks, contacts and timeline.
That makes this dialer section at least consistent and people aware if they want to search for people or make calls to exisiting people they use the dialer pad or the "find someone" search field above in that section.

Then you can leave all the rest as is.

**Comment by Elv13** [comment]
Yes, that sound likes something that could works. It already does it, but I could improve the workflow to be more search friendly. I will attack the first part of the issue (disable the organization and useless address tabs by default) and then attack this.
