### ISSUE TITLE
Tabs under Contact: change order to: Chat/Timeline - Audio/Video - Calls/Recordings - Information

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#44]
change order of these tabs to:
Chat/Timeline - Audio/Video - Calls/Recordings - Information
![screenshot_20180221_103641](https://user-images.githubusercontent.com/840070/36473141-fa651a50-16f3-11e8-925b-d084d09d00f9.png)

**Comment by Elv13** [comment]
done

**Comment by star-buck** [comment]
please mark done tickets with the green label, thanks.

**Comment by star-buck** [comment]
i dont see any of these tabs anymore on ring-kde?

**Comment by Elv13** [comment]
My bad. There is a bug in the Qt Fusion theme. I usually just patched Qt but recently upgraded and didn't notice the patch did not apply. It will be fixed in the next nightly (well, it is already fixed but I havn't finished the new nightly hosting server yet)
