### ISSUE TITLE
make releases with DATETIME stamp built into the filename

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#45]
Please adjust building releases with an actual DATETIME stamp in the release filename.

**Comment by Elv13** [comment]
So, back to square one on my own server http://lvindustries.net:8080/, hopefully I wont have NAT problems again. I will add a debug build too at some point. It's less convenient than the google drive script. There is `ring-kde-000-latest.appimage` if you wish to add a cron job to update the appimage.

Would you prefer an APT repository that keeps the appimage updated?

**Comment by star-buck** [comment]
Please add a timestamp in the filename.
No APT needed.

**Comment by Elv13** [comment]
done
